title: Bavadharini
tagline: VLSI | GATE 2026 | ECE Student
description: My Portfolio & Blog on VLSI, Verilog, and GATE preparation.
url: "https://bavadharini01.github.io"
author:
  name: Bavadharini
  email: your_email@example.com
  github: Bavadharini01
